replication controllers and services
winkapp/spark-cluster-docker pull request #2
Opened 2015-12-08 21:09 UTC by vellichor

2017-05-02 19:53 UTC, vellichor commented on deployments/production/spark-master-controller.json
> +        "generation": 3,
Is this (or anything else) cluster-side metadata that we should remove?

2017-05-02 19:55 UTC, gabe-ochoa requested changes
These are different from the running configs. Let's pull the configs off the cluster and commit those.

2017-05-02 19:55 UTC, gabe-ochoa commented on deployments/production/spark-master-controller.json
> +        "generation": 3,
@vellichor let's remove it. You're absolutely correct; it's cluster-side metadata.

2017-05-02 19:56 UTC, gabe-ochoa approved these changes
approved, but let's remove the generation metadata

2017-05-02 20:26 UTC, gabe-ochoa requested changes

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-master-service.json
> +                "nodePort": 30031,
Let's remove the nodeport so the cluster can auto assign.

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-master-service.json
> +        "resourceVersion": "3578"
resourceVersion is cluster metadata

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-master-service.json
> +                "nodePort": 31193,
same here

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-webui-service.json
> +        "resourceVersion": "3624"
- resourceVersion

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-webui-service.json
> +        "clusterIP": "10.3.0.97",
- clusteIP

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-webui-service.json
> +                "nodePort": 32441,
- nodeport

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/production/spark-webui-service.json
> +        "sessionAffinity": "None",
- sessionAffinity

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-master-service.json
> +        "resourceVersion": "14375877"
- resourceVersion

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-master-service.json
> +                "nodePort": 31565,
- nodePort

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-master-service.json
> +                "nodePort": 31093,
- nodePort

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-master-service.json
> +        "sessionAffinity": "None",
- sessionAffinity

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-webui-service.json
> +        "resourceVersion": "48587"
- resourceVersion

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-webui-service.json
> +        "clusterIP": "10.3.0.67",
- clusterIP

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-webui-service.json
> +                "nodePort": 32148,
- nodePort

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-webui-service.json
> +        "sessionAffinity": "None",
-sessionAffinity

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-worker-service.json
> +        "resourceVersion": "3986596"
- resourceVersion

2017-05-02 20:26 UTC, gabe-ochoa commented on deployments/staging/spark-worker-service.json
> +        "sessionAffinity": "None",
- sessionAffinity

2017-05-03 15:17 UTC, vellichor commented on deployments/production/spark-master-controller.json
> +                        "image": "quay.io/winkapp/spark-standalone:1.6.0",
@gabe-ochoa looks like the cluster is still running this branch image. Do you remember why? Should we move this to master?

2017-05-03 17:22 UTC, gabe-ochoa commented on deployments/production/spark-master-controller.json
> +                        "image": "quay.io/winkapp/spark-standalone:1.6.0",
@vellichor I don't but yeah let's move it to `master` now that the work is merged.

2017-05-04 15:48 UTC, gabe-ochoa approved these changes

2017-05-04 15:50 UTC, merged