includes docker-compose.yml for dev ease
winkapp/spark-cluster-docker pull request #5
Opened 2017-01-18 19:08 UTC by kalmanchapman

updates readme with docker-compose instructions

2017-01-18 19:13 UTC, gabe-ochoa requested changes

2017-01-18 19:13 UTC, gabe-ochoa commented on docker-compose.yml
> +    links:
@kalmanchapman let's open the worker webui port as well for introspection. I believe it's 4040 but check me on that.

2017-01-18 19:16 UTC, kalmanchapman commented on docker-compose.yml
> +    links:
would be very handy - only issue could be when scaling locally with `docker-compose scale` the port may already attached to a previous container. is it possible to give a range?

2017-10-04 19:49 UTC, jonhosmer approved these changes

2017-10-04 19:50 UTC, merged